#!/bin/bash
export NIGHTLY=${NIGHTLY:-no}

PLAN=(
002-wait-for-network.sh
010-disable-iptables.sh
100-aliases.sh
300-setup-epel.sh
300-setup-one-repo.sh
400-install-foreman.sh
990-updatedb.sh
)

if [ "$NIGHTLY" == "no" ]; then
  PLAN=(${PLAN[@]}
  500-configure-foreman.sh
  )
else
  PLAN=(${PLAN[@]}
  500-configure-foreman-nightly.sh
  )
fi

export PLAN
